Trainer:
  max_epochs: 5
  accelerator: gpu
  accumulate_grad_batches: 2
  log_every_n_steps: 10
  val_check_interval: 0.05
  precision: bf16-mixed

loggers:
  WandbLogger:
    project: MASTER
    name: "bert_for_patents.test_1"

callbacks:
  ModelCheckpoint:
    monitor: validation/RMSE_p
    mode: max
    dirpath: checkpoints
    filename: bert_for_patents.test_1
  RichProgressBar:
    leave: true

HP:
  device: cuda
  model: AutoModel
  pretrained_model: anferico/bert-for-patents
  learning_rate: 0.00001
  batch_size: 42
  num_workers: 16
  max_length: 384
  hardness_annealing:
    apply: true
    mode: min
    min_delta: 0.001
    patience: 10
    verbose: true
