Trainer:
  max_epochs: -1
  accelerator: gpu
  accumulate_grad_batches: 2
  log_every_n_steps: 10
  val_check_interval: 0.05
  precision: 32

loggers:
  WandbLogger:
    project: MASTER
    name: "bert_for_patents.baseline"

callbacks:
  EarlyStopping:
    monitor: validation/pearson
    mode: max
    min_delta: 0.001
    patience: 10
    verbose: true
  ModelCheckpoint:
    monitor: validation/pearson
    mode: max
    dirpath: checkpoints
    filename: bert_for_patents.baseline

HP:
  device: cuda
  model: AutoModel
  pretrained_model: anferico/bert-for-patents
  learning_rate: 0.00001
  batch_size: 52
  num_workers: 16
  max_length: 256
  pretrained_model: anferico/bert-for-patents
  
